### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by marskzj** [ExpLangcn/WanLi#3]
使用了一下，有不少环境问题，可以使用docker固定python环境以及调用的二进制的路径。

**Comment by ExpLangcn** [comment]
python环境需要配置是因为每个人和每个人的路径不同 使用方式也不同，一开始直接用的python3 但是有些人的python3是 python...这类人改动的时候就很费劲了。所以在配置的地方加入了python路径配置。

**Comment by ExpLangcn** [comment]
docker版本会尽快上线

**Comment by marskzj** [comment]
ok加油大佬
